#spring.profiles.active: prod

---
## local
spring:
  profiles: local

  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug # show sql statement
        type:
          descriptor:
            sql: trace # show sql values


---
spring:
  profiles: dev

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/sfg_dev
    username: sfg_dev_user
    password: sfg_dev_user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always # embedded db가 아닌 이상 data.sql을 읽게 하고 싶으면 세팅해야 함.
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
#    javax:
#      persistence:
#        schema-generation:
#          create-source: metadata
#          scripts:
#            action: create
#            create-target: schema-mysql.sql

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug # show sql statement
        type:
          descriptor:
            sql:
              BasicBinder: trace # show only sql binder ::values

---
spring:
  profiles: prod

  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: sfg_prod_user1234
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always # embedded db가 아닌 이상 data.sql을 읽게 하고 싶으면 세팅해야 함.
  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: debug # show sql statement
        type:
          descriptor:
            sql:
              BasicBinder: trace # show only sql binder ::values
